version: '3.9'

services:
  baza-back:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: baza-back
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    volumes:
      - baza-static:/app/baza-static
      - ./:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_NAME_DB}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD_DB}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongoData:/data/db

volumes:
  baza-static:
  mongoData:
