version: '3.9'

services:
  baza-back:
    env_file:
      - .env
    build: .
    container_name: baza-back
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    volumes:
      - baza-static:/uploads
    networks:
      - mongodb-net
      - localnet

networks:
  mongodb-net:
    external: true
    name: mongodb-net

  localnet:
    external: true
    name: localnet

volumes:
  baza-static:
